version: "3.8"
services:
  app:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:6.2-alpine
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis
volumes:
  db:
    driver: local