version: "3.8"
services:
  app:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
  redis:
    container_name: redis
    image: redis:6.2-alpine
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis