# Generated by Django 4.0.3 on 2022-04-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_article_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrappingHistory',
            new_name='ScrapingHistory',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='scrapping_history',
            new_name='scraping_history',
        ),
    ]
